// <auto-generated />
using Blackbird.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blackbird.Persistence.Migrations
{
    [DbContext(typeof(BlackbirdDbContext))]
    [Migration("20230428211807_SeedProductTestData")]
    partial class SeedProductTestData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Blackbird.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "This is product 1 description.",
                            ImageUrl = "",
                            Name = "Product 1",
                            Price = 25.99m
                        },
                        new
                        {
                            Id = 2,
                            Description = "This is product 2 description.",
                            ImageUrl = "",
                            Name = "Product 2",
                            Price = 19.99m
                        },
                        new
                        {
                            Id = 3,
                            Description = "This is product 3 description.",
                            ImageUrl = "",
                            Name = "Product 3",
                            Price = 35.50m
                        },
                        new
                        {
                            Id = 4,
                            Description = "This is product 4 description.",
                            ImageUrl = "",
                            Name = "Product 4",
                            Price = 29.99m
                        },
                        new
                        {
                            Id = 5,
                            Description = "This is product 5 description.",
                            ImageUrl = "",
                            Name = "Product 5",
                            Price = 49.99m
                        },
                        new
                        {
                            Id = 6,
                            Description = "This is product 6 description.",
                            ImageUrl = "",
                            Name = "Product 6",
                            Price = 15.99m
                        },
                        new
                        {
                            Id = 7,
                            Description = "This is product 7 description.",
                            ImageUrl = "",
                            Name = "Product 7",
                            Price = 22.99m
                        },
                        new
                        {
                            Id = 8,
                            Description = "This is product 8 description.",
                            ImageUrl = "",
                            Name = "Product 8",
                            Price = 17.99m
                        },
                        new
                        {
                            Id = 9,
                            Description = "This is product 9 description.",
                            ImageUrl = "",
                            Name = "Product 9",
                            Price = 32.99m
                        },
                        new
                        {
                            Id = 10,
                            Description = "This is product 10 description.",
                            ImageUrl = "",
                            Name = "Product 10",
                            Price = 24.99m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
