// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Blackbird.Persistence.Migrations
{
    [DbContext(typeof(BlackbirdDbContext))]
    partial class BlackbirdDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Blackbird.Domain.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "This is product 1 description.",
                            ImageUrl = "",
                            Name = "Product 1",
                            Price = 25.99m,
                            ProductId = "d9d3857d-17a4-4acd-8e82-dbe87510f26c"
                        },
                        new
                        {
                            Id = 2,
                            Description = "This is product 2 description.",
                            ImageUrl = "",
                            Name = "Product 2",
                            Price = 19.99m,
                            ProductId = "fc142e5a-d247-4b25-8295-c86317146043"
                        },
                        new
                        {
                            Id = 3,
                            Description = "This is product 3 description.",
                            ImageUrl = "",
                            Name = "Product 3",
                            Price = 35.50m,
                            ProductId = "0cc082ec-754d-4fb3-837e-c1d7e3086e75"
                        },
                        new
                        {
                            Id = 4,
                            Description = "This is product 4 description.",
                            ImageUrl = "",
                            Name = "Product 4",
                            Price = 29.99m,
                            ProductId = "b7f83fe2-461f-4dee-9ca2-74ca00454d32"
                        },
                        new
                        {
                            Id = 5,
                            Description = "This is product 5 description.",
                            ImageUrl = "",
                            Name = "Product 5",
                            Price = 49.99m,
                            ProductId = "eb8b8c2b-37c1-4dde-b60d-4402d4114e54"
                        },
                        new
                        {
                            Id = 6,
                            Description = "This is product 6 description.",
                            ImageUrl = "",
                            Name = "Product 6",
                            Price = 15.99m,
                            ProductId = "c9b7f15f-79de-4d8b-af68-62e3197ca2ee"
                        },
                        new
                        {
                            Id = 7,
                            Description = "This is product 7 description.",
                            ImageUrl = "",
                            Name = "Product 7",
                            Price = 22.99m,
                            ProductId = "2c2affc1-5228-462c-ad98-61dd1570c47b"
                        },
                        new
                        {
                            Id = 8,
                            Description = "This is product 8 description.",
                            ImageUrl = "",
                            Name = "Product 8",
                            Price = 17.99m,
                            ProductId = "48e57660-6b9b-4348-a472-d87047a1638f"
                        },
                        new
                        {
                            Id = 9,
                            Description = "This is product 9 description.",
                            ImageUrl = "",
                            Name = "Product 9",
                            Price = 32.99m,
                            ProductId = "18d431a8-d17a-428e-a519-3a9526228d70"
                        },
                        new
                        {
                            Id = 10,
                            Description = "This is product 10 description.",
                            ImageUrl = "",
                            Name = "Product 10",
                            Price = 24.99m,
                            ProductId = "2ff61626-363f-482b-b465-8acedb8424b9"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
